### ISSUE TITLE
error: cannot decrypt

### ISSUE THREAD

**Issue by titoesteves** [bitwarden/jslib#681] opened 2022-02-14 00:39 UTC
Hi I am seeing `error: cannot decrypt` when using bitwarden. Issue seems to happen most often when computer(either mac or pc) comes back on from sleep mode. In order to resolve, I often have to exit all chrome windows and restart chrome. 

Any ideas on how to resolve the root problem? Any details I can gather to help troubleshoot this issue?

Screenshot: https://i.imgur.com/ibAz6vo.png

Details: 
- Chrome version 98.0.4758.80
- Mac OS Catalina

Please advise.

**Comment by Hinton** [comment] 2022-02-14 12:45
Closed as a duplicate of https://github.com/bitwarden/browser/issues/2334

**Closed by Hinton** 2022-02-14 12:45 UTC
